# Generated by Django 3.0 on 2019-12-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0002_weatherfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherfiles',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
