# Generated by Django 3.0 on 2019-12-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0003_auto_20191203_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherfiles',
            name='file',
            field=models.FileField(default='NULL', upload_to=''),
            preserve_default=False,
        ),
    ]
